# figVG_forest.R — FigVG: forest plot of log2FC (rLLB vs. Control) for voltage-gated Na+/K+/Ca2+ channels
# and their auxiliary subunits, plus FigVG_ext (adds the "Related" block). Self-contained: if the objects of
# R/00_setup.R (dds, theme, helpers) are not in the session, they are sourced here.
# Statistics (log2FC, lfcSE, pvalue, padj, baseMean) come ONLY from results/deseq2_R_results_no_exclusion.csv
# (DESeq2 run2, no gene exclusion, no LFC shrinkage). DESeq2 `dds` is used for normalised counts and Cook's distance.
# Usage (repository root): Rscript R/figVG_forest.R

if (!exists("dds")) {
  invisible(Sys.setlocale("LC_ALL", "C.UTF-8"))
  write_qc_report <- function() invisible(NULL)        # 00_setup.R's report hook (Fig. 1–6 ledger); not used here
  source("R/00_setup.R", encoding = "UTF-8")
  source("R/theme_ijms.R", encoding = "UTF-8")
}
stopifnot(exists("theme_ijms"), exists("save_fig"), exists("p_stars"))

## ------------------------------------------------------------ VG ledger ---
vg_checks <- data.frame(section = character(), check = character(), expected = character(),
                        obtained = character(), ok = logical(), stringsAsFactors = FALSE)
vg_notes <- list()
vg_check <- function(section, check, expected, obtained, ok) {
  vg_checks[nrow(vg_checks) + 1, ] <<- list(section, check, as.character(expected), as.character(obtained), isTRUE(ok))
  cat(sprintf("[VG %s] %-52s expected %-26s obtained %-26s %s\n", section, check, expected, obtained,
              if (isTRUE(ok)) "OK" else "MISMATCH"))
  invisible(isTRUE(ok))
}
vg_note <- function(section, ...) vg_notes[[section]] <<- c(vg_notes[[section]], paste0(...))
vg_title <- c(`4.1` = "Counts by status (section 4.1)", `4.2` = "Reference values (section 4.2)",
              `4.3.1` = "Symbols not found in counts", `4.3.2` = "Genes not detected (n.d.): absent vs. filtered",
              `4.3.3` = "Genes with low_expr (mean normalised counts < 5 in at least one group)",
              `4.3.4` = "Genes beyond the x axis", `4.3.5` = "Cook's distance", Layout = "Layout",
              Fonts = "Fonts and files", Session = "sessionInfo()", Source = "Gene list and nomenclature")
write_vg_report <- function() {
  f <- file.path(dir_fig, "figure_qc_VG.md")
  md <- c("# Figure QC report (FigVG, FigVG_ext)", "",
          sprintf("Generated by `R/figVG_forest.R` on %s. Statistics: `results/deseq2_R_results_no_exclusion.csv` (DESeq2 run2, no gene exclusion), padj < 0.05, no log2FC threshold, no LFC shrinkage.",
                  format(Sys.time(), "%Y-%m-%d %H:%M %Z")), "")
  if (!is.null(vg_notes[["STOP"]])) md <- c(md, "## STOPPED", "", paste0("**", vg_notes[["STOP"]], "**"), "")
  md <- c(md, "## Checks: expected / obtained / OK", "", "| section | check | expected | obtained | OK |", "|---|---|---|---|---|",
          sprintf("| %s | %s | %s | %s | %s |", vg_checks$section, gsub("|", "\\|", vg_checks$check, fixed = TRUE),
                  vg_checks$expected, vg_checks$obtained, ifelse(vg_checks$ok, "✅", "❌")), "")
  for (s in setdiff(names(vg_notes), "STOP")) {
    md <- c(md, paste0("## ", if (s %in% names(vg_title)) vg_title[[s]] else s), "")
    md <- c(md, unlist(lapply(vg_notes[[s]], function(x) c(x, ""))))
  }
  writeLines(md, f); message("wrote ", f)
}
vg_stop_if_failed <- function(sections) {
  bad <- vg_checks[vg_checks$section %in% sections & !vg_checks$ok, ]
  if (nrow(bad) > 0) {
    vg_note("STOP", "Stopped after section(s) ", paste(sections, collapse = ", "), ": ",
            paste(sprintf("%s (expected %s, obtained %s)", bad$check, bad$expected, bad$obtained), collapse = "; "),
            ". Figures were not built; no parameters were adjusted to the expected numbers.")
    write_vg_report()
    stop("VG QC failed: ", paste(bad$check, collapse = "; "))
  }
}

## ----------------------------------------------------- 1. gene list + stats ---
path_vg <- "scripts/voltage_gated_genes.csv"
genes <- read.csv(path_vg, fileEncoding = "UTF-8", stringsAsFactors = FALSE)
genes <- genes[order(genes$order), ]
stopifnot(identical(colnames(genes), c("class", "family", "role", "tier", "gene", "protein", "order")))
vg_check("4.1", "Genes in list (core / auxiliary / extended)", "110 (60 / 34 / 16)",
         sprintf("%d (%s)", nrow(genes), paste(table(factor(genes$tier, c("core", "auxiliary", "extended"))), collapse = " / ")),
         nrow(genes) == 110 && identical(as.integer(table(factor(genes$tier, c("core", "auxiliary", "extended")))), c(60L, 34L, 16L)))
vg_check("4.1", "Gene symbols unique", "TRUE", !anyDuplicated(genes$gene), !anyDuplicated(genes$gene))

ref_vg <- read.csv(path_ref_res, check.names = FALSE, stringsAsFactors = FALSE)
m <- match(genes$gene, ref_vg$gene_id)                       # exact, case-sensitive
genes$baseMean       <- ref_vg$baseMean[m]
genes$log2FoldChange <- ref_vg$log2FoldChange[m]
genes$lfcSE          <- ref_vg$lfcSE[m]
genes$pvalue         <- ref_vg$pvalue[m]
genes$padj           <- ref_vg$padj[m]

# Counts: presence of the symbol and the sum over 8 samples (rounded counts, as passed to DESeq2).
in_counts  <- genes$gene %in% symbols
count_sum  <- ifelse(in_counts, rowSums(cnt)[match(genes$gene, rownames(cnt))], NA)
nc <- counts(dds, normalized = TRUE)
genes$mean_norm_Control <- rowMeans(nc[match(genes$gene, rownames(nc)), ctrl_ids, drop = FALSE])
genes$mean_norm_rLLB    <- rowMeans(nc[match(genes$gene, rownames(nc)), bw_ids, drop = FALSE])

genes$status <- ifelse(is.na(m), "n.d.",
                       ifelse(is.na(genes$padj), "n.t.",
                              ifelse(genes$padj >= 0.05, "ns", ifelse(genes$log2FoldChange < 0, "down", "up"))))
genes$nd_reason <- ifelse(genes$status != "n.d.", NA_character_,
                          ifelse(!in_counts, "absent from counts",
                                 ifelse(count_sum < 10, "filtered (rowSums < 10)", "UNEXPLAINED")))
genes$low_expr <- !is.na(genes$mean_norm_Control) & (genes$mean_norm_Control < 5 | genes$mean_norm_rLLB < 5)
genes$on_plot  <- genes$status %in% c("down", "up", "ns")

## ------------------------------------------------------------------- 4.1 ---
exp_tab <- rbind(core = c(10, 1, 24, 4, 21), auxiliary = c(5, 1, 18, 2, 8), extended = c(4, 0, 7, 0, 5))
colnames(exp_tab) <- c("down", "up", "ns", "n.t.", "n.d.")
for (t in rownames(exp_tab)) {
  got <- as.integer(table(factor(genes$status[genes$tier == t], colnames(exp_tab))))
  vg_check("4.1", paste0("Status counts, ", t, " (down/up/ns/n.t./n.d.)"), paste(exp_tab[t, ], collapse = " / "),
           paste(got, collapse = " / "), all(got == exp_tab[t, ]))
}
sets_exp <- list(
  list("core", "down", c("Scn1a", "Scn5a", "Cacna1c", "Cacna1d", "Cacna1a", "Cacna1g", "Cacna1h", "Kcna5", "Kcng1", "Kcnh2")),
  list("core", "up", "Kcnh7"),
  list("core", "n.t.", c("Cacna1e", "Kcna6", "Kcnc2", "Kcnq2")),
  list("auxiliary", "down", c("Scn3b", "Cacnb3", "Cacna2d2", "Cacng6", "Kcne4")),
  list("auxiliary", "up", "Cacna2d4"),
  list("auxiliary", "n.t.", c("Cacng5", "Kcnab1")),
  list("extended", "down", c("Hcn4", "Kcnt1", "Tpcn1", "Tpcn2")))
for (s in sets_exp) {
  got <- genes$gene[genes$tier == s[[1]] & genes$status == s[[2]]]
  vg_check("4.1", sprintf("Gene list %s %s", s[[1]], s[[2]]), paste(sort(s[[3]]), collapse = ","),
           paste(sort(got), collapse = ","), setequal(got, s[[3]]))
}

## ------------------------------------------------------------------- 4.2 ---
refv <- data.frame(gene = c("Scn5a", "Cacna1c", "Kcnh2", "Kcna5", "Scn3b", "Hcn4", "Kcnq1", "Scn1b", "Kcnip2"),
                   lfc = c(-0.957, -0.797, -0.949, -1.157, -2.059, -1.904, -0.116, -0.010, -0.020),
                   padj = c(3.3e-5, 0.0017, 2.2e-4, 4.2e-5, 4.1e-9, 1.9e-7, 0.53, 0.98, 0.96))
for (i in seq_len(nrow(refv))) {
  g <- refv$gene[i]; r <- genes[genes$gene == g, ]
  ok <- nrow(r) == 1 && !is.na(r$padj) && abs(r$log2FoldChange - refv$lfc[i]) <= 0.001 && signif(r$padj, 2) == refv$padj[i]
  vg_check("4.2", paste0("Reference value ", g), sprintf("%s; %s", fmt_num(refv$lfc[i], 3), fmt_p_txt(refv$padj[i])),
           sprintf("%s; %s", fmt_num(r$log2FoldChange, 3), fmt_p_txt(r$padj)), ok)
}
vg_stop_if_failed(c("4.1", "4.2"))

## ----------------------------------------------------------------- 4.3.1-2 ---
vg_check("4.3.1", "Symbols not found in counts", 0, sum(!in_counts), sum(!in_counts) == 0)
vg_note("4.3.1", if (any(!in_counts)) paste0("Not found (no similar symbol was searched): ", paste(genes$gene[!in_counts], collapse = ", "))
        else "All 110 symbols were found in the counts file (exact, case-sensitive match).")
nd <- genes[genes$status == "n.d.", ]
vg_check("4.3.2", "n.d. genes with unexplained absence", 0, sum(nd$nd_reason == "UNEXPLAINED"), all(nd$nd_reason != "UNEXPLAINED"))
nd_cnt <- count_sum[genes$status == "n.d."]
vg_note("4.3.2", sprintf("%d genes are n.d.: %d absent from the counts file, %d filtered by rowSums >= 10.",
                         nrow(nd), sum(nd$nd_reason == "absent from counts"), sum(nd$nd_reason == "filtered (rowSums < 10)")))
vg_note("4.3.2", paste(c("| gene | tier | reason | sum of counts (8 samples) |", "|---|---|---|---|",
                         sprintf("| *%s* | %s | %s | %s |", nd$gene, nd$tier, nd$nd_reason, ifelse(is.na(nd_cnt), "–", nd_cnt))), collapse = "\n"))

## --------------------------------------------------------------- 4.3.3 ---
le <- genes[genes$low_expr, ]
vg_note("4.3.3", sprintf("%d genes drawn with a hollow marker (%d on the figure).", nrow(le), sum(le$on_plot)))
vg_note("4.3.3", paste(c("| gene | tier | status | log2FC | mean norm. counts Control | mean norm. counts rLLB |", "|---|---|---|---|---|---|",
                         sprintf("| *%s* | %s | %s | %s | %.2f | %.2f |", le$gene, le$tier, le$status,
                                 ifelse(is.na(le$log2FoldChange), "NA", fmt_num(le$log2FoldChange, 2)),
                                 le$mean_norm_Control, le$mean_norm_rLLB)), collapse = "\n"))

## ------------------------------------------------------- figure geometry ---
XL <- c(-3.5, 3.5)
row_mm <- 3.7; gap_mm <- 1.5; top_mm <- 6; pcol_mm <- 18
genes$beyond_axis <- genes$on_plot & (genes$log2FoldChange > XL[2] | genes$log2FoldChange < XL[1])
genes$family_f <- factor(genes$family, unique(genes$family))
bey <- genes[genes$beyond_axis, ]
vg_note("4.3.4", sprintf("x axis limits %s…%s. Beyond: %s.", fmt_num(XL[1], 1), paste0("+", XL[2]),
                         paste(sprintf("*%s* %s%s (%s)", bey$gene, ifelse(bey$log2FoldChange > 0, "+", ""),
                                       sub("^-", MINUS, formatC(bey$log2FoldChange, format = "f", digits = 2)), bey$tier), collapse = ", ")))
vg_check("4.3.4", "Beyond axis (core + auxiliary): Cacna2d4, Kcnh7", "Cacna2d4, Kcnh7",
         paste(sort(bey$gene[bey$tier != "extended"]), collapse = ", "),
         setequal(bey$gene[bey$tier != "extended"], c("Cacna2d4", "Kcnh7")) &&
           all(genes$low_expr[genes$gene %in% c("Cacna2d4", "Kcnh7")]))

hdr_html <- "<span style='color:#595959'>auxiliary subunits</span>"

# Rows of one panel: genes on the plot of the given classes, with an "auxiliary subunits" sub-header row
# inserted before the first auxiliary family of each class.
make_rows <- function(classes, tiers) {
  d <- genes[genes$class %in% classes & genes$tier %in% tiers & genes$on_plot, ]
  d <- d[order(d$order), ]
  fams <- unique(d$family)
  out <- list()
  for (f in fams) {
    x <- d[d$family == f, ]
    cl <- x$class[1]
    first_aux_of_class <- x$tier[1] == "auxiliary" && !any(d$class == cl & d$tier == "auxiliary" & d$order < min(x$order))
    if (first_aux_of_class) {
      blank <- x[1, setdiff(names(x), "family"), drop = FALSE]
      blank[1, ] <- NA
      out[[length(out) + 1]] <- cbind(data.frame(fam = paste0("hdr_", cl), id = paste0("hdr_", cl), lab = hdr_html,
                                                 is_hdr = TRUE, stringsAsFactors = FALSE), blank)
    }
    r <- cbind(data.frame(fam = f, id = x$gene, lab = sprintf("*%s* (%s)", x$gene, x$protein), is_hdr = FALSE,
                          stringsAsFactors = FALSE), x[, setdiff(names(x), "family"), drop = FALSE])
    out[[length(out) + 1]] <- r
  }
  r <- do.call(rbind, out)
  r$fam <- factor(r$fam, unique(r$fam))
  r$id_f <- factor(r$id, rev(r$id))
  r$y <- ave(seq_len(nrow(r)), r$fam, FUN = function(i) rev(seq_along(i)))   # position inside the facet (1 = bottom)
  r$status[r$is_hdr] <- NA
  r
}

# Whiskers, clipping and labels (rows that are not headers).
prep_rows <- function(r) {
  r$x <- ifelse(r$is_hdr, 0, pmin(pmax(r$log2FoldChange, XL[1]), XL[2]))
  r$clip_hi <- !r$is_hdr & r$log2FoldChange > XL[2]
  r$clip_lo <- !r$is_hdr & r$log2FoldChange < XL[1]
  r$lo <- r$log2FoldChange - r$lfcSE; r$hi <- r$log2FoldChange + r$lfcSE
  r$wl <- pmax(r$lo, XL[1]); r$wh <- pmin(r$hi, XL[2])
  r$w_draw <- !r$is_hdr & r$wl < r$wh
  r$cap_lo <- r$w_draw & r$lo >= XL[1]; r$cap_hi <- r$w_draw & r$hi <= XL[2]
  r$p_lab <- ifelse(r$is_hdr, NA, ifelse(r$status == "ns", '"ns"', fmt_p_math(r$padj, 2)))
  r$stars <- ifelse(r$is_hdr | r$status == "ns", NA, p_stars(r$padj))
  r
}

tri_df <- function(r) {                                       # triangles pointing outwards at the axis edge
  b <- r[r$clip_hi | r$clip_lo, ]
  if (!nrow(b)) return(b[0, c("id", "status", "low_expr")][, c("id", "status", "low_expr")])
  do.call(rbind, lapply(seq_len(nrow(b)), function(i) {
    s <- if (b$clip_hi[i]) 1 else -1
    data.frame(id = b$id[i], status = b$status[i], low_expr = b$low_expr[i], fam = b$fam[i],
               px = XL[if (s > 0) 2 else 1] - s * c(0, 0.34, 0.34),
               py = b$y[i] + c(0, 0.34, -0.34))
  }))
}

strip_lab <- function(x) ifelse(grepl("^hdr_", x), "", sub(" \\(", "\n(", x))

miss_text <- function(r_all, classes, tiers) {
  x <- genes[genes$class %in% classes & genes$tier %in% tiers & genes$status %in% c("n.t.", "n.d."), ]
  line <- function(st) {
    y <- x[x$status == st, ]
    if (!nrow(y)) return("none")
    parts <- vapply(split(y$gene, droplevels(y$family_f)), function(g) paste0("*", g, "*", collapse = ", "), character(1))
    # digit/digit inside bold text falls back to DejaVu in gridtext: keep the slash outside the bold span
    fam_md <- gsub("(?<=[0-9])/(?=[0-9])", "**/**", names(parts), perl = TRUE)
    paste(sprintf("**%s:** %s", fam_md, parts), collapse = "; ")
  }
  md <- paste0("**Not tested** (padj = NA): ", line("n.t."), "; **not detected:** ", line("n.d."))
  plain <- gsub("[*]", "", md)
  list(md = md, n_lines = ceiling(nchar(plain) / 62))
}

# One panel = a single ggplot (forest + padj/stars columns drawn outside the plot area, so rows always align)
# converted to a gtable whose panel heights are fixed in mm (row pitch = row_mm); the n.t./n.d. note is a gridtext box.
col_w <- 84                                                   # mm; two columns on a 170-mm page, 2-mm gutter
page_w <- 170

build_panel <- function(classes, tiers, tag, unit_mm = 5, star_mm = 11.5) {
  r <- prep_rows(make_rows(classes, tiers))
  nrow_tot <- nrow(r); nfac <- nlevels(r$fam)
  lab <- setNames(r$lab, r$id)
  tri <- tri_df(r)
  nm <- r[!r$is_hdr, ]
  base <- theme_ijms() +
    theme(axis.text.y = ggtext::element_markdown(size = 7, family = FONT, hjust = 1, colour = "black"),
          axis.ticks.y = element_blank(),
          strip.placement = "outside", strip.text.y.left = element_text(angle = 0, hjust = 1, face = "bold", size = 7,
                                                                       lineheight = 0.9),
          panel.spacing.y = unit(gap_mm, "mm"), strip.clip = "off",
          plot.margin = margin(top_mm, pcol_mm, 1, 1, "mm"), plot.tag.position = c(0, 1))
  xp <- XL[2] + 0.2                                           # padj column starts just right of the axis
  pF <- ggplot(r, aes(x, id_f)) +
    geom_blank() +
    geom_vline(xintercept = 0, linewidth = lw_axis, colour = "#808080", linetype = "dashed") +
    geom_segment(data = nm[nm$w_draw, ], aes(x = wl, xend = wh, yend = id_f, colour = status), linewidth = lw_whisker) +
    geom_segment(data = nm[nm$cap_lo, ], aes(x = lo, xend = lo, y = y - 0.25, yend = y + 0.25, colour = status), linewidth = lw_whisker) +
    geom_segment(data = nm[nm$cap_hi, ], aes(x = hi, xend = hi, y = y - 0.25, yend = y + 0.25, colour = status), linewidth = lw_whisker) +
    geom_point(data = nm[!nm$clip_hi & !nm$clip_lo & !nm$low_expr, ], aes(colour = status), size = 1.6) +
    geom_point(data = nm[!nm$clip_hi & !nm$clip_lo & nm$low_expr, ], aes(colour = status), shape = 21, fill = "white",
               size = 1.6, stroke = 0.5) +
    geom_polygon(data = tri[!tri$low_expr, ], aes(px, py, group = id, colour = status, fill = status), linewidth = 0.2,
                 inherit.aes = FALSE) +
    geom_polygon(data = tri[tri$low_expr, ], aes(px, py, group = id, colour = status), fill = "white", linewidth = 0.4,
                 inherit.aes = FALSE) +
    geom_text(data = nm[nm$clip_hi, ], aes(x = XL[2] - 0.45, label = paste0("+", formatC(log2FoldChange, format = "f", digits = 2))),
              hjust = 1, size = 6 / PT, family = FONT) +
    geom_text(data = nm[nm$clip_lo, ], aes(x = XL[1] + 0.45, label = fmt_num(log2FoldChange, 2)),
              hjust = 0, size = 6 / PT, family = FONT) +
    geom_text(data = nm, aes(x = xp, label = p_lab), parse = TRUE, hjust = 0, size = 6.5 / PT, family = FONT) +
    geom_text(data = nm[!is.na(nm$stars), ], aes(x = xp + star_mm / unit_mm, label = stars), hjust = 0, size = 6.5 / PT, family = FONT) +
    facet_grid(fam ~ ., scales = "free_y", space = "free_y", switch = "y", labeller = as_labeller(strip_lab)) +
    scale_colour_manual(values = dir_cols, guide = "none") + scale_fill_manual(values = dir_cols, guide = "none") +
    scale_y_discrete(labels = function(i) lab[as.character(i)], expand = expansion(add = 0.5)) +
    scale_x_continuous(breaks = seq(-3, 3, 1), labels = lab_minus) +
    coord_cartesian(xlim = XL, expand = FALSE, clip = "off") +
    labs(x = expression(log[2] ~ "fold change (rLLB vs. Control)"), y = NULL, tag = tag) +
    base

  g <- ggplotGrob(pF)
  pan <- g$layout[grepl("^panel", g$layout$name), ]
  pan <- pan[order(pan$t), ]
  n_per <- as.integer(table(r$fam)[levels(r$fam)])
  g$heights[pan$t] <- unit(n_per * row_mm, "mm")             # fixed row pitch
  g$widths[unique(pan$l)] <- unit(1, "null")

  mt <- miss_text(r, classes, tiers)
  tg <- gridtext::textbox_grob(mt$md, x = unit(0, "mm"), y = unit(1, "npc"), hjust = 0, vjust = 1, halign = 0,
                               width = unit(col_w - 1, "mm"), padding = unit(c(0, 0, 0, 0), "mm"),
                               gp = grid::gpar(fontsize = 6.5, fontfamily = FONT, lineheight = 1.25),
                               box_gp = grid::gpar(col = NA, fill = NA))
  list(gt = g, tg = tg, pan_first = pan[1, ], rows = r, n_rows = sum(!r$is_hdr), n_hdr = sum(r$is_hdr))
}

# Measure (mm) a built panel on a scratch device, so that the page height follows from the content.
measure_panel <- function(P) {
  grDevices::cairo_pdf(tempfile(fileext = ".pdf"), width = 6, height = 8, family = FONT)
  on.exit(invisible(dev.off()))
  grid::pushViewport(grid::viewport(width = unit(col_w, "mm"), height = unit(250, "mm")))
  P$h_gt <- grid::convertHeight(sum(P$gt$heights), "mm", valueOnly = TRUE)
  P$h_tg <- grid::convertHeight(grid::grobHeight(P$tg), "mm", valueOnly = TRUE)
  P$top_above_panel <- grid::convertHeight(sum(P$gt$heights[seq_len(P$pan_first$t - 1)]), "mm", valueOnly = TRUE)
  P$right_of_panel <- grid::convertWidth(sum(P$gt$widths[(P$pan_first$r + 1):length(P$gt$widths)]), "mm", valueOnly = TRUE)
  P$panel_w <- col_w - grid::convertWidth(sum(P$gt$widths[-unique(P$pan_first$l)]), "mm", valueOnly = TRUE)
  P$h <- P$h_gt + 1 + P$h_tg
  P
}

# Draw a panel with its top-left corner at (x0, y_top) mm on the page.
draw_panel <- function(P, x0, y_top) {
  grid::pushViewport(grid::viewport(x = unit(x0, "mm"), y = unit(y_top, "mm"), width = unit(col_w, "mm"),
                                    height = unit(P$h_gt, "mm"), just = c("left", "top")))
  grid::grid.draw(P$gt)
  grid::grid.text("padj", x = unit(col_w - P$right_of_panel + 1.2, "mm"), y = unit(P$h_gt - P$top_above_panel + 0.8, "mm"),
                  just = c("left", "bottom"), gp = grid::gpar(fontsize = 7, fontface = "bold", fontfamily = FONT))
  grid::popViewport()
  grid::pushViewport(grid::viewport(x = unit(x0, "mm"), y = unit(y_top - P$h_gt - 1, "mm"), width = unit(col_w, "mm"),
                                    height = unit(P$h_tg, "mm"), just = c("left", "top")))
  grid::grid.draw(P$tg)
  grid::popViewport()
}

## ------------------------------------------------------------- build figs ---
build_all <- function(u = c(A = 5, B = 5, C = 5)) list(          # u: mm per x unit of each panel
  A = measure_panel(build_panel(c("Nav", "Cav"), c("core", "auxiliary"), "A", u[["A"]])),
  B = measure_panel(build_panel("Kv", c("core", "auxiliary"), "B", u[["B"]])),
  C = measure_panel(build_panel("Related", "extended", "C", u[["C"]])))
P1 <- build_all()                                            # first pass: measure panel widths
P2 <- build_all(vapply(P1, function(P) P$panel_w / diff(XL), numeric(1)))
pA <- P2$A; pB <- P2$B; pC <- P2$C
x_left <- 0; x_right <- page_w - col_w
gap_panels <- 3

H_main <- ceiling(max(pA$h, pB$h) + 1)
fig_main <- function() {
  grid::grid.newpage()
  draw_panel(pA, x_left, H_main); draw_panel(pB, x_right, H_main)
}
H_ext <- ceiling(max(pA$h + gap_panels + pC$h, pB$h) + 1)
fig_ext <- function() {
  grid::grid.newpage()
  draw_panel(pA, x_left, H_ext); draw_panel(pC, x_left, H_ext - pA$h - gap_panels)
  draw_panel(pB, x_right, H_ext)
}

on_main <- pA$n_rows + pB$n_rows
vg_check("Layout", "Genes on FigVG (core + auxiliary, down/up/ns)", "59", on_main, on_main == 59)
vg_check("Layout", "Genes on FigVG_ext panel C", "11", pC$n_rows, pC$n_rows == 11)
vg_note("Layout", sprintf("Row pitch %.1f mm (requirement >= 3.5 mm); gaps between families %.1f mm. Rows: panel A %d (+%d sub-header rows), panel B %d (+%d), panel C %d.",
                          row_mm, gap_mm, pA$n_rows, pA$n_hdr, pB$n_rows, pB$n_hdr, pC$n_rows))
vg_note("Layout", sprintf("Page height FigVG %.1f cm, FigVG_ext %.1f cm (limit 23 cm).", H_main / 10, H_ext / 10))
vg_check("Layout", "Height FigVG / FigVG_ext <= 23 cm", "TRUE", sprintf("%.1f / %.1f cm", H_main / 10, H_ext / 10),
         H_main <= 230 && H_ext <= 230)
vg_check("Layout", "Row pitch >= 3.5 mm", "TRUE", row_mm, row_mm >= 3.5)

save_fig(fig_main, "FigVG", 17, H_main / 10)
save_fig(fig_ext, "FigVG_ext", 17, H_ext / 10)

## ------------------------------------------------------------ source data ---
src <- genes[, c("class", "family", "role", "tier", "gene", "protein", "baseMean", "log2FoldChange", "lfcSE", "pvalue",
                 "padj", "mean_norm_Control", "mean_norm_rLLB", "status", "low_expr", "on_plot", "beyond_axis", "nd_reason")]
write_src(src, "FigVG_forest")
vg_check("Layout", "Source data rows", 110, nrow(src), nrow(src) == 110)

## ------------------------------------------------------------- legend ---
n_list <- nrow(genes); n_core_aux <- sum(genes$tier != "extended")
n_fig <- sum(genes$on_plot & genes$tier != "extended"); n_ext <- sum(genes$on_plot)
cnt_tier <- function(t, s) sum(genes$tier %in% t & genes$status == s)
legend <- c(
  "# FigVG — draft legend (English)", "",
  sprintf(paste0("**Figure X. Differential expression of voltage-gated Na⁺, Ca²⁺ and K⁺ channel genes and their auxiliary subunits in rLLB hearts relative to Control.** ",
                 "Forest plot of log₂ fold change (rLLB vs. Control; DESeq2, Wald test, n = 4 per group, no log₂FC shrinkage). ",
                 "Dots show log₂ fold change and whiskers show ± lfcSE (standard error of the log₂ fold change). ",
                 "(A) Nav and Cav; (B) Kv. Genes are grouped by family (pore-forming α subunits first, then auxiliary subunits). ",
                 "Blue, significantly decreased (padj < 0.05); red, significantly increased (padj < 0.05); grey, not significant (ns); no log₂ fold-change threshold was applied. ",
                 "padj, Benjamini–Hochberg-adjusted p value; * padj < 0.05, ** < 0.01, *** < 0.001, **** < 0.0001. ",
                 "Hollow markers, genes with low expression (mean DESeq2-normalised counts < 5 in at least one group; in Control ≈ 0 for the genes shown beyond the axis). ",
                 "Triangles at the edge of the axis, values beyond the plotted range (the log₂ fold change is given next to the triangle). ",
                 "Genes with padj = NA after independent filtering (not tested) and genes not detected (filtered at ≥ 10 counts over 8 samples, or absent) are listed below each panel and are not drawn. ",
                 "The list comprises %d genes (%d core pore-forming and %d auxiliary); %d are shown. Gene families and protein names follow the IUPHAR/BPS Guide to Pharmacology nomenclature. ",
                 "Gene symbols are rat symbols."),
          n_core_aux, sum(genes$tier == "core"), sum(genes$tier == "auxiliary"), n_fig), "",
  sprintf("Core: %d down, %d up, %d ns, %d not tested, %d not detected. Auxiliary: %d down, %d up, %d ns, %d not tested, %d not detected.",
          cnt_tier("core", "down"), cnt_tier("core", "up"), cnt_tier("core", "ns"), cnt_tier("core", "n.t."), cnt_tier("core", "n.d."),
          cnt_tier("auxiliary", "down"), cnt_tier("auxiliary", "up"), cnt_tier("auxiliary", "ns"), cnt_tier("auxiliary", "n.t."),
          cnt_tier("auxiliary", "n.d.")), "",
  "# FigVG_ext (Supplementary) — draft legend", "",
  sprintf(paste0("**Figure S-X. As FigVG, extended with related channels.** Panel C adds channels that are voltage-dependent or related but are not Nav/Cav/Kv by IUPHAR/BPS: ",
                 "HCN, BK, Slo-like (KNa/KCa5.1), CatSper, TPC, Hv1 and NALCN. The list comprises %d genes (%d core, %d auxiliary, %d extended); %d are shown (%d in panel C). ",
                 "Symbols, markers, whiskers (± lfcSE), arrows and thresholds are as in FigVG; the value beyond the axis in panel C is *Kcnt1* (low expression, hollow triangle)."),
          n_list, sum(genes$tier == "core"), sum(genes$tier == "auxiliary"), sum(genes$tier == "extended"), n_ext, n_ext - n_fig), "",
  sprintf("Extended: %d down, %d up, %d ns, %d not tested, %d not detected.", cnt_tier("extended", "down"), cnt_tier("extended", "up"),
          cnt_tier("extended", "ns"), cnt_tier("extended", "n.t."), cnt_tier("extended", "n.d.")), "")
writeLines(legend, file.path(dir_fig, "FigVG_legend.md"))

## ---------------------------------------------------------- Cook's distance ---
cooks_vg <- assays(dds)[["cooks"]]
p_coef <- ncol(model.matrix(design(dds), colData(dds))); m_s <- ncol(dds)
cook_cut <- qf(0.99, p_coef, m_s - p_coef)
cg <- c("Scn5a", "Cacna1c", "Kcnh2", "Kcna5", "Hcn4")
ck <- do.call(rbind, lapply(cg, function(g) {
  v <- cooks_vg[g, samples_order]
  data.frame(gene = g, t(round(v, 3)), max_sample = names(which.max(v)), max_cooks = max(v), above = max(v) > cook_cut, check.names = FALSE)
}))
vg_note("4.3.5", sprintf("DESeq2 default Cook's cutoff qf(0.99, %d, %d) = %.2f (no outlier replacement with n = 4 per group).", p_coef, m_s - p_coef, cook_cut))
vg_note("4.3.5", paste(c(paste0("| gene | ", paste(samples_order, collapse = " | "), " | extreme animal | max D | > cutoff |"),
                         paste0("|", strrep("---|", length(samples_order) + 4)),
                         apply(ck, 1, function(r) paste0("| *", r[["gene"]], "* | ", paste(r[samples_order], collapse = " | "), " | ",
                                                         r[["max_sample"]], " | ", sprintf("%.3f", as.numeric(r[["max_cooks"]])), " | ", r[["above"]], " |"))),
                       collapse = "\n"))
write_src(ck, "FigVG_cooks_distance")

## ----------------------------------------------------------- source note ---
vg_note("Source", "Gene list: `scripts/voltage_gated_genes.csv` (110 genes; IUPHAR/BPS Guide to Pharmacology family names). ",
        "Compared with the project copy `voltage_gated_NaKCa_genes.csv` (set via env var `VG_REF_CSV`): ",
        if (nzchar(Sys.getenv("VG_REF_CSV")) && file.exists(Sys.getenv("VG_REF_CSV"))) {
          up <- data.table::fread(Sys.getenv("VG_REF_CSV"), data.table = FALSE, encoding = "UTF-8")
          k <- match(genes$gene, up$rat_symbol)
          st_up <- ifelse(grepl("^n\\.t\\.", up$status[k]), "n.t.", ifelse(grepl("^отфильтрован", up$status[k]), "n.d.", up$status[k]))
          sprintf("same symbol set: %s; same tier: %s; same status (down/up/ns/n.t./n.d.): %s; max |dlog2FC| = %.1e; max |dpadj| = %.1e.",
                  setequal(genes$gene, up$rat_symbol) && !anyNA(k), all(genes$tier == up$tier[k]), all(genes$status == st_up),
                  max(abs(genes$log2FoldChange - up$log2FoldChange[k]), na.rm = TRUE),
                  max(abs(genes$padj - up$padj[k]), na.rm = TRUE))
        } else "not available in this run (not compared).")
vg_note("Source", "Statuses: down/up = padj < 0.05 by sign; ns = padj >= 0.05; n.t. = in the DESeq2 output with padj = NA; n.d. = not in the output.",
        " Mean normalised counts: `counts(dds, normalized = TRUE)`; the `dds` is rebuilt in `R/00_setup.R` and verified against the reference CSV there (rule 0.1).",
        " DESeq2 version in this run: ", as.character(packageVersion("DESeq2")), " (R ", getRversion(), ").")

## ----------------------------------------------------------- fonts / files ---
for (p in file.path(dir_fig, c("FigVG.pdf", "FigVG_ext.pdf"))) {
  if (nzchar(Sys.which("pdffonts"))) {
    pf <- system2("pdffonts", p, stdout = TRUE)
    fams <- unique(sub("^[A-Z]{6}\\+", "", vapply(strsplit(trimws(pf[-(1:2)]), "\\s+"), `[`, "", 1)))
    embedded <- all(grepl("yes", substr(pf[-(1:2)], 1, 200)))
    vg_check("Fonts", paste0("pdffonts ", basename(p)), "Arial only, embedded",
             paste0(paste(fams, collapse = ", "), if (embedded) " (emb)" else " (NOT all emb)"),
             length(fams) > 0 && all(grepl("^Arial", fams)) && embedded)
  } else vg_note("Fonts", "pdffonts not available: font embedding not verified.")
}
if (nzchar(Sys.which("tiffinfo"))) for (t in file.path(dir_fig, c("FigVG.tiff", "FigVG_ext.tiff"))) {
  ti <- system2("tiffinfo", t, stdout = TRUE, stderr = TRUE)
  vg_note("Fonts", basename(t), ": ", paste(trimws(grep("Resolution|Compression|Image Width", ti, value = TRUE)), collapse = "; "))
}
vg_note("Session", paste(c("```", capture.output(sessionInfo()), "```"), collapse = "\n"))
write_vg_report()
if (any(!vg_checks$ok)) message("Some VG checks failed: see figures/figure_qc_VG.md") else message("All VG checks passed.")
