# Writes results/figure_qc.md. Sourced by run_all.R after all figures are built.

if (!exists("ROOT")) ROOT <- normalizePath(".")
source(file.path(ROOT, "R", "helpers.R"))

d <- get_data()
res <- d$res
panel <- d$panel
panel_ch <- subset(panel, module == "channel")
out <- character()
say <- function(...) out <<- c(out, paste0(...))
fmt <- function(x, k = 3) formatC(x, format = "fg", digits = k, flag = "#")
mismatch <- data.frame(check = character(), expected = character(), obtained = character())
chk <- function(name, expected, obtained, ok) {
  if (!isTRUE(ok)) mismatch[nrow(mismatch) + 1, ] <<- c(name, expected, obtained)
  if (isTRUE(ok)) "✅" else "❌"
}
md_table <- function(df) {
  c(paste0("| ", paste(names(df), collapse = " | "), " |"),
    paste0("|", paste(rep("---", ncol(df)), collapse = "|"), "|"),
    apply(df, 1, function(r) paste0("| ", paste(r, collapse = " | "), " |")))
}

say("# Figure QC report")
say("")
say("Generated by `Rscript R/run_all.R` on ", format(Sys.time(), "%Y-%m-%d %H:%M %Z"), ".")
say("R ", R.version$major, ".", R.version$minor, "; DESeq2 ", as.character(packageVersion("DESeq2")),
    "; ggplot2 ", as.character(packageVersion("ggplot2")),
    "; ComplexHeatmap ", as.character(packageVersion("ComplexHeatmap")), ".")
say("")
say("Statistics source: `results/deseq2_R_results_no_exclusion.csv` (DESeq2 1.42.1, R 4.3.3, ",
    "Bioconductor 3.18; run 2, no mito/rRNA exclusion). DESeq2 was **not** re-run: the DESeq2 object ",
    "here is used only for size factors, normalized counts and VST.")
say("")

## 1 ----------------------------------------------------------------------------
n_filt <- nrow(d$counts); n_padj <- sum(!is.na(res$padj))
same_genes <- setequal(rownames(d$counts), res$gene_id)
say("## 1. Filtering, padj, baseMean")
say("")
say(md_table(data.frame(
  check = c("genes after rowSums ≥ 10", "gene set identical to DESeq2 output", "genes with padj",
            "max relative deviation, baseMean vs. mean(normalized counts)"),
  expected = c("18 114", "yes", "17 362", "< 1e-6"),
  obtained = c(n_filt, ifelse(same_genes, "yes", "no"), n_padj, formatC(d$bm_rel, format = "e", digits = 2)),
  status = c(chk("genes after filter", "18114", n_filt, n_filt == 18114),
             chk("gene set identical", "yes", same_genes, same_genes),
             chk("genes with padj", "17362", n_padj, n_padj == 17362),
             chk("baseMean max rel. deviation", "< 1e-6", signif(d$bm_rel, 3), d$bm_rel < 1e-6)))))
say("")
say("Size factors (DESeq2 median-of-ratios): ",
    paste(sprintf("%s %.4f", SAMPLES, sizeFactors(d$dds)[SAMPLES]), collapse = ", "), ".")
say("")

## 2 ----------------------------------------------------------------------------
n_sig <- sum(res$direction != "NS"); n_dn <- sum(res$direction == "Down"); n_up <- sum(res$direction == "Up")
say("## 2. DEGs at padj < 0.05")
say("")
say(md_table(data.frame(check = c("DEGs", "down", "up"), expected = c(5390, 2563, 2827),
                        obtained = c(n_sig, n_dn, n_up),
                        status = c(chk("DEGs", 5390, n_sig, n_sig == 5390), chk("DEGs down", 2563, n_dn, n_dn == 2563),
                                   chk("DEGs up", 2827, n_up, n_up == 2827)))))
say("")

## Panel -----------------------------------------------------------------------
say("## Panel definition (Table 1) — `data/panel_table1.csv`")
say("")
say("No panel definition file was found in the repository, so `data/panel_table1.csv` was ",
    "reconstructed (92 channel genes, 16 families + 21 scaffold genes). All control numbers match; ",
    "see the note on the two ambiguous families below.")
say("")
fam_exp <- c("ENaC/ASIC" = 9, PIEZO = 2, K2P = 14, TRPC = 7, TRPV = 6, TRPM = 8, TRPA = 1, TRPML = 3,
             TRPP = 7, "TMEM16/ANO" = 10, TMEM63 = 3, TMC = 8, TMEM150C = 1, KCNMA1 = 1, LRRC8 = 5, ClC = 7)
st <- gene_status(panel_ch$gene, res)
dirs <- res[match(panel_ch$gene, res$gene_id), "direction"]
fam_tab <- do.call(rbind, lapply(names(fam_exp), function(f) {
  s <- panel_ch$family == f
  data.frame(family = f, expected = fam_exp[[f]], genes = sum(s), with_padj = sum(st[s] == "padj"),
             n.t. = sum(st[s] == "n.t."), n.d. = sum(st[s] == "n.d."),
             down = sum(dirs[s] == "Down", na.rm = TRUE), up = sum(dirs[s] == "Up", na.rm = TRUE),
             members = paste(panel_ch$gene[s], collapse = ", "))
}))
say(md_table(fam_tab))
say("")
kcnk17_ann <- "Kcnk17" %in% rownames(d$raw)
n_pp <- sum(st == "padj"); n_pd <- sum(dirs == "Down", na.rm = TRUE); n_pu <- sum(dirs == "Up", na.rm = TRUE)
fam_ok <- all(fam_tab$genes == fam_tab$expected)
say(md_table(data.frame(
  check = c("channel genes", "families with expected size", "Kcnk17 in annotation", "genes with padj",
            "down at padj < 0.05", "up at padj < 0.05"),
  expected = c(92, "16/16", "no", 62, 20, 3),
  obtained = c(nrow(panel_ch), paste0(sum(fam_tab$genes == fam_tab$expected), "/16"),
               ifelse(kcnk17_ann, "yes", "no"), n_pp, n_pd, n_pu),
  status = c(chk("panel genes", 92, nrow(panel_ch), nrow(panel_ch) == 92),
             chk("panel family sizes", "16/16", sum(fam_tab$genes == fam_tab$expected), fam_ok),
             chk("Kcnk17 absent", "no", kcnk17_ann, !kcnk17_ann),
             chk("panel genes with padj", 62, n_pp, n_pp == 62),
             chk("panel down", 20, n_pd, n_pd == 20), chk("panel up", 3, n_pu, n_pu == 3)))))
say("")
say("**Reconstruction choices to confirm.** Two families have one more canonical member than the target ",
    "count, and the choice changes only which non-significant/undetected gene is listed:")
say("")
say("- **TRPP (7)**: polycystin family Pkd1, Pkd1l1, Pkd1l2, Pkd1l3, Pkd2, Pkd2l1, Pkd2l2; **Pkdrej excluded** ",
    "(sperm receptor, padj = 0.23, would add a 63rd tested gene).")
say("- **K2P (14)**: Kcnk1–7, 9, 10, 12, 13, 16, 17, 18; **Kcnk15 excluded** (TASK-5, non-functional; not in the ",
    "DESeq2 output, so it affects only the n.d. list).")
say("- The alternative 'Kcnk7 out, Pkdrej in' also gives 62 / 20 / 3. If the original Table 1 differs, edit ",
    "`data/panel_table1.csv` and re-run; every figure and this report are regenerated from it.")
say("- `class` (MS = directly mechanosensitive, MR = mechanoresponsive) was assigned from the literature: ",
    "MS = ", paste(panel_ch$gene[panel_ch$class == "MS"], collapse = ", "), "; all other channels MR.")
say("")

## 3 ----------------------------------------------------------------------------
f1 <- .bw$fig1
rs <- f1$ratio_summ
ratio_v <- d$ncounts["Myh7", SAMPLES] / d$ncounts["Myh6", SAMPLES]
welch_log <- t.test(log10(ratio_v) ~ GROUP[SAMPLES])
say("## 3. Myh7/Myh6 ratio (Fig. 1A)")
say("")
say(md_table(data.frame(group = rs$group, n = rs$n, mean = fmt(rs$mean), SD = fmt(rs$sd, 2), SEM = fmt(rs$sem, 2))))
say("")
say("The expected values (rLLB 0.47 ± 0.23, Control0.068 ± 0.027) are **mean ± SD**. The figure shows mean ± SEM.")
say("Welch t-test on the linear ratio (as drawn): t = ", fmt(unname(f1$welch$statistic)), ", df = ",
    fmt(unname(f1$welch$parameter)), ", p = ", fmt(f1$welch$p.value), ". For reference, Welch on log10(ratio): p = ",
    fmt(welch_log$p.value), " (not used).")
say("")
m_r <- rs$mean[rs$group == "rLLB"]; s_r <- rs$sd[rs$group == "rLLB"]
m_s <- rs$mean[rs$group == "Control"]; s_s <- rs$sd[rs$group == "Control"]
say(md_table(data.frame(check = c("rLLB mean ± SD", "Controlmean ± SD", "Welch p"),
  expected = c("0.47 ± 0.23", "0.068 ± 0.027", "≈ 0.036"),
  obtained = c(sprintf("%.2f ± %.2f", m_r, s_r), sprintf("%.3f ± %.3f", m_s, s_s), sprintf("%.3f", f1$welch$p.value)),
  status = c(chk("Myh7/Myh6 rLLB", "0.47 ± 0.23", sprintf("%.2f ± %.2f", m_r, s_r), round(m_r, 2) == 0.47 && round(s_r, 2) == 0.23),
             chk("Myh7/Myh6 Control", "0.068 ± 0.027", sprintf("%.3f ± %.3f", m_s, s_s), round(m_s, 3) == 0.068 && round(s_s, 3) == 0.027),
             chk("Welch p", "0.036", sprintf("%.3f", f1$welch$p.value), round(f1$welch$p.value, 3) == 0.036)))))
say("")

## 4 ----------------------------------------------------------------------------
f3 <- .bw$fig3
pc1 <- f3$pca$PC1; grp <- f3$pca$group
sep <- max(pc1[grp == "Control"]) < min(pc1[grp == "rLLB"]) || min(pc1[grp == "Control"]) > max(pc1[grp == "rLLB"])
say("## 4. PCA (Fig. 3A)")
say("")
say("VST: `vst(dds, blind = TRUE)`; `plotPCA(ntop = 500)`. PC1 = ", sprintf("%.1f%%", 100 * f3$pv[1]),
    ", PC2 = ", sprintf("%.1f%%", 100 * f3$pv[2]), ".")
say("")
say(md_table(data.frame(check = c("PC1 variance", "complete separation of groups on PC1"),
  expected = c("≈ 47.6 %", "yes"), obtained = c(sprintf("%.1f %%", 100 * f3$pv[1]), ifelse(sep, "yes", "no")),
  status = c(chk("PC1 variance", "47.6 %", sprintf("%.1f %%", 100 * f3$pv[1]), abs(100 * f3$pv[1] - 47.6) < 0.1),
             chk("PC1 separation", "yes", ifelse(sep, "yes", "no"), sep)))))
say("")
# Where could 47.6 % come from? Variants (diagnostic only; the figure uses the spec).
pv_of <- function(m, ntop = 500) {
  rv <- apply(m, 1, var); sel <- order(rv, decreasing = TRUE)[seq_len(min(ntop, nrow(m)))]
  p <- prcomp(t(m[sel, ])); 100 * p$sdev^2 / sum(p$sdev^2)
}
vm <- SummarizedExperiment::assay(d$vsd); lg <- log2(d$ncounts + 1)
pc_var <- data.frame(
  input = c("VST (blind), ntop = 500 — **figure (spec)**", "VST (blind), all 18 114 genes",
            "log2(normalized + 1), ntop = 500", "log2(normalized + 1), all 18 114 genes"),
  PC1 = sprintf("%.1f %%", c(pv_of(vm)[1], pv_of(vm, Inf)[1], pv_of(lg)[1], pv_of(lg, Inf)[1])),
  PC2 = sprintf("%.1f %%", c(pv_of(vm)[2], pv_of(vm, Inf)[2], pv_of(lg)[2], pv_of(lg, Inf)[2])))
say("PC1 share under alternative inputs (diagnostic, not used in the figure):")
say("")
say(md_table(pc_var))
say("")
say("The expected 47.6 % is reproduced (±0.1) only by a PCA of log2(normalized counts + 1) over all genes; ",
    "the specified VST + top-500 PCA gives ", sprintf("%.1f %%", 100 * f3$pv[1]), " (the earlier run-1 PCA in ",
    "`results/PCA_vst.png` also reported 64 %). The figure is drawn as specified; update the text or the ",
    "specification, not the figure, if 47.6 % is quoted in the manuscript.")
say("")
say("PC coordinates and library composition per sample:")
say("")
pp <- f3$pca
say(md_table(data.frame(sample = pp$sample, group = pp$group, PC1 = sprintf("%.2f", pp$PC1),
                        PC2 = sprintf("%.2f", pp$PC2), library_size = format(round(pp$lib_size), big.mark = " "),
                        mito_frac = sprintf("%.4f", pp$mito_frac), rRNA_frac = formatC(pp$rrna_frac, format = "e", digits = 2))))
say("")
say("Correlation of PC1 with library covariates (n = 8; not shown in the figure):")
say("")
pcc <- f3$pc1_cor
say(md_table(data.frame(variable = c("library size", "mitochondrial fraction", "rRNA fraction"),
                        pearson_r = sprintf("%.3f", pcc$pearson_r), pearson_p = fmt(pcc$pearson_p, 2),
                        spearman_rho = sprintf("%.3f", pcc$spearman_rho), spearman_p = fmt(pcc$spearman_p, 2))))
say("")
say("Mitochondrial genes: ", paste(MITO_GENES, collapse = ", "), " (+ `mt-*`); rRNA: `^Rn(5|5-8|18|28|45)s$`. ",
    "Fractions are of total raw (rounded) counts over all annotated genes.")
say("")
say("Volcano (Fig. 3B): ", f3$n_padj, " genes with padj; ", f3$n_down, " down / ", f3$n_up,
    " up; ", f3$n_clamped, " genes with |log2FC| > 8 drawn as triangles at the ±8 edge.")
say("")

## 5 ----------------------------------------------------------------------------
f4 <- .bw$fig4
or <- unname(f4$fisher$estimate); fp <- f4$fisher$p.value
say("## 5. Fisher exact test (Fig. 4A)")
say("")
say(md_table(data.frame(set = rownames(f4$tab), down = f4$tab[, "Down"], up = f4$tab[, "Up"])))
say("")
say("Two-sided `fisher.test`: conditional MLE OR = ", sprintf("%.3f", or), " (95% CI ",
    sprintf("%.2f–%.2f", f4$fisher$conf.int[1], f4$fisher$conf.int[2]), "), p = ", formatC(fp, format = "e", digits = 3),
    "; sample OR (20/3)/(2543/2824) = ", sprintf("%.3f", (f4$tab[1, 1] / f4$tab[1, 2]) / (f4$tab[2, 1] / f4$tab[2, 2])), ".")
say("")
say(md_table(data.frame(check = c("Genome down/up (panel removed)", "OR", "p"),
  expected = c("2543 / 2824", "7.40", "1.8 × 10⁻⁴"),
  obtained = c(paste(f4$tab[2, 1], "/", f4$tab[2, 2]), sprintf("%.2f", or), fmt_p_txt(fp)),
  status = c(chk("Genome down/up", "2543 / 2824", paste(f4$tab[2, 1], "/", f4$tab[2, 2]), all(f4$tab[2, ] == c(2543, 2824))),
             chk("Fisher OR", "7.40", sprintf("%.2f", or), sprintf("%.2f", or) == "7.40"),
             chk("Fisher p", "1.8e-4", signif(fp, 2), signif(fp, 2) == 1.8e-4)))))
say("")

## 6 ----------------------------------------------------------------------------
nl <- f4$null
say("## 6. Permutation test (Fig. 4B)")
say("")
say("No original permutation script (Python, seed 1) was found in the repository, so the test was ",
    "re-implemented in R (`R/fig4.R`, `set.seed(1)`): for each of the 62 panel genes with padj, one gene is ",
    "drawn uniformly from the 200 non-panel genes with padj nearest in log10(baseMean); 2000 permutations. ",
    "The null distribution is in `source_data/Fig4B_null.csv`. Because the RNG differs from the Python original, ",
    "exact agreement is not expected; agreement within Monte-Carlo error is.")
say("")
ms <- function(x) sprintf("%.1f ± %.1f", mean(x), sd(x))
ms2 <- function(x) sprintf("%.2f ± %.2f (MC s.e. of mean %.2f)", mean(x), sd(x), sd(x) / sqrt(length(x)))
say(md_table(data.frame(statistic = c("down", "up", "down − up"), expected = c("7.7 ± 2.5", "9.2 ± 2.7", "−1.5 ± 4.1"),
  obtained = gsub("-", "−", c(ms(nl$down), ms(nl$up), ms(nl$diff))),
  status = c(chk("perm down", "7.7 ± 2.5", ms(nl$down), ms(nl$down) == "7.7 ± 2.5"),
             chk("perm up", "9.2 ± 2.7", ms(nl$up), ms(nl$up) == "9.2 ± 2.7"),
             chk("perm down−up", "−1.5 ± 4.1", gsub("-", "−", ms(nl$diff)), ms(nl$diff) == "-1.5 ± 4.1")))))
say("")
say("Unrounded: down ", ms2(nl$down), "; up ", ms2(nl$up), "; down − up ", gsub("-", "−", ms2(nl$diff)),
    ". The 0.1 differences from the expected values are about two Monte-Carlo standard errors of the ",
    "mean, i.e. consistent with a different random stream (R vs. Python); the SDs agree.")
say("")
say("Observed down − up = ", f4$obs, "; permutations with down − up ≥ observed: ", f4$n_ge, "/", nrow(nl),
    " (max in null = ", max(nl$diff), ").")
say("")

## 7 ----------------------------------------------------------------------------
say("## 7. Figure files")
say("")
pdf_min_font <- function(pdf) {
  tmp <- tempfile(fileext = ".pdf")
  system2("qpdf", c("--qdf", "--object-streams=disable", shQuote(pdf), shQuote(tmp)))
  txt <- readLines(tmp, warn = FALSE, encoding = "latin1")
  txt <- iconv(txt, "latin1", "UTF-8", sub = "")
  # cairo writes text as: "<a> <b> <c> <d> <e> <f> Tm" + "/f-x-y <s> Tf"
  tf <- as.numeric(sub("/f-[0-9-]+ ([0-9.]+) Tf", "\\1",
                       unlist(regmatches(txt, gregexpr("/f-[0-9-]+ [0-9.]+ Tf", txt)))))
  tm <- unlist(regmatches(txt, gregexpr("[-0-9.]+ [-0-9.]+ [-0-9.]+ [-0-9.]+ [-0-9.]+ [-0-9.]+ Tm", txt)))
  sz <- vapply(strsplit(tm, " "), function(v) sqrt(as.numeric(v[1])^2 + as.numeric(v[2])^2), 0)
  # Font size = Tf size × Tm scale; cairo uses one of the two as 1.
  s <- if (length(tf) && all(tf == 1)) sz else if (length(sz) && all(abs(sz - 1) < 1e-6)) tf else c(tf, sz)
  unlink(tmp)
  if (!length(s)) return(NA)
  min(round(s, 2))
}
tiff_info <- function(f) {
  con <- file(f, "rb"); on.exit(close(con))
  bo <- rawToChar(readBin(con, "raw", 2)); en <- if (bo == "II") "little" else "big"
  readBin(con, "integer", 1, size = 2, endian = en)
  off <- readBin(con, "integer", 1, size = 4, endian = en)
  seek(con, off); n <- readBin(con, "integer", 1, size = 2, signed = FALSE, endian = en)
  tags <- list()
  for (i in seq_len(n)) {
    tag <- readBin(con, "integer", 1, size = 2, signed = FALSE, endian = en)
    type <- readBin(con, "integer", 1, size = 2, signed = FALSE, endian = en)
    cnt <- readBin(con, "integer", 1, size = 4, endian = en)
    val <- if (type == 3) { v <- readBin(con, "integer", 1, size = 2, signed = FALSE, endian = en); readBin(con, "raw", 2); v }
           else readBin(con, "integer", 1, size = 4, endian = en)
    tags[[as.character(tag)]] <- c(type = type, val = val)
  }
  rational <- function(off) { pos <- seek(con); seek(con, off)
    v <- readBin(con, "integer", 2, size = 4, endian = en); seek(con, pos); v[1] / v[2] }
  list(width = tags[["256"]][["val"]], height = tags[["257"]][["val"]],
       compression = c(`1` = "none", `5` = "LZW", `8` = "Deflate")[as.character(tags[["259"]][["val"]])],
       photometric = c(`1` = "grey", `2` = "RGB")[as.character(tags[["262"]][["val"]])],
       spp = tags[["277"]][["val"]], xres = rational(tags[["282"]][["val"]]))
}
figs <- c("Fig1", "Fig3", "Fig4", "Fig5", "Fig6")
ft <- do.call(rbind, lapply(figs, function(f) {
  pdf <- file.path(dir_fig, paste0(f, ".pdf")); tif <- file.path(dir_fig, paste0(f, ".tiff"))
  info <- system2("pdfinfo", shQuote(pdf), stdout = TRUE)
  ps <- as.numeric(regmatches(grep("Page size", info, value = TRUE), gregexpr("[0-9.]+", grep("Page size", info, value = TRUE)))[[1]][1:2])
  fonts <- system2("pdffonts", shQuote(pdf), stdout = TRUE)[-(1:2)]
  fam <- unique(sub("^[A-Z]{6}\\+", "", vapply(strsplit(trimws(fonts), "\\s+"), `[`, "", 1)))
  emb <- all(grepl(" yes ", fonts))
  ti <- tiff_info(tif)
  data.frame(figure = f, pdf_size_cm = sprintf("%.2f × %.2f", ps[1] / 72 * 2.54, ps[2] / 72 * 2.54),
             min_font_pt = pdf_min_font(pdf), pdf_fonts = paste(fam, collapse = ", "),
             all_embedded = ifelse(emb, "yes", "no"),
             tiff = sprintf("%d × %d px, %.0f dpi, %s, %s", ti$width, ti$height, ti$xres, ti$compression,
                            ifelse(ti$photometric == "RGB", paste0("RGB", if (ti$spp == 4) "A" else ""), ti$photometric)))
}))
say(md_table(ft))
say("")
arial_only <- all(grepl("^Arial", unlist(strsplit(ft$pdf_fonts, ", "))))
min_font <- min(ft$min_font_pt, na.rm = TRUE)
chk("fonts", "Arial only, embedded", paste(unique(ft$pdf_fonts), collapse = "; "), arial_only && all(ft$all_embedded == "yes"))
chk("min font", "≥ 6 pt", min_font, min_font >= 6 - 1e-6)
say("Figures are drawn at 17.00 cm; cairo writes the PDF page size in whole points (481 pt = 16.97 cm). ",
    "Minimum font size is read from the text matrices of the decompressed PDF (qpdf). Background points of the ",
    "volcano are rasterised (ggrastr, 600 dpi); everything else is vector.")
if (isTRUE(.bw$fig5$split_D)) say("Fig. 5D was split into D1/D2.") else
  say("Fig. 5: panel D fits in two rows of 10 facets; no D1/D2 split was needed (height ",
      sprintf("%.1f", .bw$fig5$height_cm), " cm).")
say("")

## 8 ----------------------------------------------------------------------------
spec_genes <- unique(c("Myh6", "Myh7", "Ptprc", "Cd68", "Adgre1", "Mrc1", "Csf1r", "Tcf21", "Pdgfra",
  "Col1a1", "Col3a1", "Postn", "Eln", "Fbn1", "Piezo1", "Piezo2", "Kcnk2", "Kcnk3", "Tmc6", "Tmem63a",
  "Pkd1", "Ano6", "Trpm4", "Lrrc8a", "Lrrc8c", "Mcoln2", "Kcnk4", panel$gene))
sg <- data.frame(gene = spec_genes, in_annotation = spec_genes %in% rownames(d$raw),
                 in_output = spec_genes %in% res$gene_id,
                 padj_NA = spec_genes %in% res$gene_id[is.na(res$padj)])
sg$raw_total <- ifelse(sg$in_annotation, rowSums(d$raw[match(spec_genes, rownames(d$raw)), , drop = FALSE]), NA)
fam_of <- setNames(panel$family, panel$gene)
say("## 8. Specification genes missing from the DESeq2 output")
say("")
nd <- subset(sg, !in_output)
say("n.d. (not in the output; ", nrow(nd), " genes):")
say("")
say(md_table(data.frame(gene = nd$gene, family = fam_of[nd$gene],
                        reason = ifelse(nd$in_annotation, paste0("filtered (rowSums = ", nd$raw_total, " < 10)"),
                                        "not in the annotation"), row.names = NULL)))
say("")
nt <- subset(sg, padj_NA)
say("n.t. (in the output, padj = NA — independent filtering / Cook's outliers; ", nrow(nt), " genes): ",
    paste(sprintf("*%s*", nt$gene), collapse = ", "), ".")
say("")
say("All Fig. 1, Fig. 3B-label and Fig. 6 genes are present in the output with padj.")
say("")

## Summary (placed at the top of the report) ---------------------------------------
top <- c("## Discrepancies: expected vs. obtained", "",
         if (nrow(mismatch)) md_table(mismatch) else "None — every control number was reproduced.", "",
         "Details and explanations are in the numbered sections below. Nothing was adjusted to match.", "")
intro_end <- which(out == "## 1. Filtering, padj, baseMean") - 1
out <- c(out[seq_len(intro_end)], top, out[-seq_len(intro_end)])

writeLines(out, file.path(ROOT, "results", "figure_qc.md"))
