#!/usr/bin/env Rscript
# Builds Fig. 1–6, source data, table2 and figures/figure_qc.md.
# Usage (from the repository root): Rscript R/run_all.R

write_qc_report <- function() {
  f <- file.path(dir_fig, "figure_qc.md")
  md <- c("# Figure QC report (Fig. 1–6)", "",
          sprintf("Generated by `R/run_all.R` on %s. Statistics: DESeq2 run2 (no gene exclusion), padj < 0.05, no log2FC threshold, no LFC shrinkage.",
                  format(Sys.time(), "%Y-%m-%d %H:%M %Z")), "")
  if (!is.null(qc_notes[["STOP"]])) md <- c(md, "## STOPPED", "", paste0("**", qc_notes[["STOP"]], "**"), "")
  sec_title <- c(`2.1` = "1. Counts and DESeq2 (section 2.1)", `2.3` = "TPM files (section 2.3)",
                 `2.4` = "Panel (section 2.4)", `2.5` = "Modules outside the panel (section 2.5)",
                 Fig1 = "Fig. 1", Fig2 = "Fig. 2", Fig3 = "Fig. 3", Fig4 = "Fig. 4", Fig5 = "Fig. 5", Fig6 = "Fig. 6",
                 Cooks = "Cook's distance", Fonts = "Fonts", Session = "sessionInfo()")
  md <- c(md, "## Checks: expected / obtained / OK", "",
          "| section | check | expected | obtained | OK |", "|---|---|---|---|---|",
          sprintf("| %s | %s | %s | %s | %s |", qc_checks$section, gsub("|", "\\|", qc_checks$check, fixed = TRUE),
                  qc_checks$expected, qc_checks$obtained, ifelse(qc_checks$ok, "✅", "❌")), "")
  for (s in setdiff(names(qc_notes), "STOP")) {
    md <- c(md, paste0("## ", if (s %in% names(sec_title)) sec_title[[s]] else s), "")
    md <- c(md, unlist(lapply(qc_notes[[s]], function(x) c(x, ""))))
  }
  writeLines(md, f)
  message("wrote ", f)
}

# Non-ASCII glyphs (−, ×, ↓, ±) need a UTF-8 locale for cairo/pango.
invisible(Sys.setlocale("LC_ALL", "C.UTF-8"))
source("R/00_setup.R", encoding = "UTF-8")
source("R/theme_ijms.R", encoding = "UTF-8")

fm <- systemfonts::match_font("Arial")   # systemfonts 1.0.x API (match_fonts() in >= 1.1)
qc_check("Fonts", "systemfonts::match_font('Arial')", "arial.ttf", basename(fm$path), grepl("arial", fm$path, ignore.case = TRUE))
qc_stop_if_failed("Fonts")

for (f in c("R/fig1_purity.R", "R/fig2_channelome_tpm.R", "R/fig3_pca_volcano.R",
            "R/fig4_selectivity.R", "R/fig5_forest.R", "R/fig6_scaffold_heatmap.R")) {
  message("=== ", f, " ===")
  source(f, encoding = "UTF-8")
}

## ------------------------------------------------------ table 2 ---
t2_genes <- rbind(data.frame(set = "panel", family = panel$family, subgroup = panel$subfamily, gene = panel$gene),
                  do.call(rbind, lapply(names(modules), function(fg) do.call(rbind, lapply(names(modules[[fg]]), function(b)
                    data.frame(set = paste0("module (", sub("fig", "Fig. ", fg), ")"), family = b, subgroup = b,
                               gene = modules[[fg]][[b]]))))),
                  data.frame(set = "module (Fig. 1)", family = "Cardiomyocyte", subgroup = "Cardiomyocyte",
                             gene = c("Myh6", "Myh7")))
t2 <- cbind(t2_genes, de[match(t2_genes$gene, de$gene),
                         c("baseMean", "log2FC", "lfcSE", "pvalue", "padj", "mean_norm_Control", "mean_norm_rLLB")])
t2$status <- ifelse(!t2$gene %in% de$gene, "n.d.", de[match(t2$gene, de$gene), "dir"])
names(t2)[names(t2) == "log2FC"] <- "log2FoldChange"
write.csv(t2, file.path(dir_fig, "table2_panel_deseq2.csv"), row.names = FALSE)

## ------------------------------------------------------ Cook's distance ---
cooks <- assays(dds)[["cooks"]]
p_coef <- ncol(model.matrix(design(dds), colData(dds))); m_s <- ncol(dds)
cook_cut <- qf(0.99, p_coef, m_s - p_coef)
qc_note("Cooks", sprintf("DESeq2 default Cook's cutoff qf(0.99, %d, %d) = %.2f (outlier replacement needs >= 7 replicates; n = 4 per group, so none).",
                         p_coef, m_s - p_coef, cook_cut))
cook_tab <- do.call(rbind, lapply(c("Piezo1", "Kcnk2", "Tmc6", "Trpm4"), function(g) {
  cg <- cooks[g, samples_order]
  data.frame(gene = g, t(round(cg, 3)), max_sample = names(which.max(cg)), max_cooks = max(cg),
             above_cutoff = max(cg) > cook_cut, check.names = FALSE)
}))
qc_note("Cooks", paste(c(paste0("| gene | ", paste(samples_order, collapse = " | "), " | extreme animal | max D | > cutoff |"),
                         paste0("|", strrep("---|", length(samples_order) + 4)),
                         apply(cook_tab, 1, function(r) paste0("| *", r[["gene"]], "* | ",
                                                              paste(r[samples_order], collapse = " | "), " | ", r[["max_sample"]], " | ",
                                                              sprintf("%.3f", as.numeric(r[["max_cooks"]])), " | ", r[["above_cutoff"]], " |"))),
                       collapse = "\n"))
write_src(cook_tab, "QC_cooks_distance")

## ------------------------------------------------------ summary notes ---
qc_note("Fig3", "PC1 correlation with technical covariates (per sample, n = 8):\n\n",
        paste(c("| covariate | Pearson r (8) | p | Spearman rho (8) | r within Control | r within rLLB |",
                "|---|---|---|---|---|---|",
                sprintf("| %s | %.3f | %s | %.3f | %.3f | %.3f |", cor_tab$covariate, cor_tab$pearson_r_all8,
                        fmt_p_txt(cor_tab$p_all8), cor_tab$spearman_rho_all8, cor_tab$r_within_Control, cor_tab$r_within_rLLB)),
              collapse = "\n"),
        "\n\nrRNA_frac = genes `^Rn[0-9]` (true rRNA/snRNA); Rn_prefix_frac = the old `^Rn` & nchar < 8 mask (incl. Rnf*/Rnase*).",
        " Within-group r uses 4 points and is descriptive only.")
qc_note("Fig4", "fry results (voom on the same 18 114 genes, TMM, ~ condition, coefficient conditionblast; BH over tested families):\n\n",
        paste(c("| set | n genes | rLLB/Control | manuscript | Direction | PValue | FDR | dominant gene (share) |",
                "|---|---|---|---|---|---|---|---|",
                sprintf("| %s | %d | %.3f | %s | %s | %s | %s | *%s* (%.0f %%) |", famC$set, famC$n_genes, famC$ratio,
                        ifelse(is.na(famC$ratio_manuscript), "–", sprintf("%.2f", famC$ratio_manuscript)),
                        ifelse(famC$tested, famC$fry_Direction, "single gene"),
                        ifelse(famC$tested, fmt_p_txt(famC$fry_PValue), "–"),
                        ifelse(famC$tested, fmt_p_txt(famC$FDR), "–"), famC$dominant_gene, 100 * famC$dominant_share)),
              collapse = "\n"))

## ------------------------------------------------------ fonts in PDFs ---
pdfs <- file.path(dir_fig, paste0("Fig", 1:6, ".pdf"))
if (nzchar(Sys.which("pdffonts"))) {
  for (p in pdfs) {
    pf <- system2("pdffonts", p, stdout = TRUE)
    fams <- unique(sub("^[A-Z]{6}\\+", "", vapply(strsplit(trimws(pf[-(1:2)]), "\\s+"), `[`, "", 1)))
    embedded <- all(grepl("yes", substr(pf[-(1:2)], 1, 200)))
    ok <- length(fams) > 0 && all(grepl("^Arial", fams))
    qc_check("Fonts", paste0("pdffonts ", basename(p)), "Arial only, embedded",
             paste0(paste(fams, collapse = ", "), if (embedded) " (emb)" else " (NOT all emb)"), ok && embedded)
  }
} else qc_note("Fonts", "pdffonts not available: font embedding not verified.")
tiffs <- file.path(dir_fig, paste0("Fig", 1:6, ".tiff"))
if (nzchar(Sys.which("tiffinfo"))) for (t in tiffs) {
  ti <- system2("tiffinfo", t, stdout = TRUE, stderr = TRUE)
  qc_note("Fonts", basename(t), ": ", paste(trimws(grep("Resolution|Compression|Samples/Pixel|Photometric", ti, value = TRUE)), collapse = "; "))
}

qc_note("Session", paste(c("```", capture.output(sessionInfo()), "```"), collapse = "\n"))
write_qc_report()
if (any(!qc_checks$ok)) message("Some checks failed: see figures/figure_qc.md") else message("All checks passed.")
